CREATE TABLE IF NOT EXISTS `payam_tamas` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `nam` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) DEFAULT NULL,
    `telefon` VARCHAR(50) DEFAULT NULL,
    `mozoo` VARCHAR(100) DEFAULT NULL,
    `payam` TEXT NOT NULL,
    `ip_address` VARCHAR(45) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
