CREATE TABLE IF NOT EXISTS mahsul_brand (
    id INT AUTO_INCREMENT PRIMARY KEY,
    onvan VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    logo VARCHAR(500) DEFAULT NULL,
    tozih TEXT,
    tartib INT DEFAULT 0,
    vaziat TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE mahsulat ADD COLUMN brand_id INT DEFAULT NULL AFTER dasteh_id;
